/**
 * drizzle persistence accepts a small repository object generated by the caller's schema.
 */
import { persistenceadapter } from "./adapter.js";

export function drizzlepersistence(repository) {
  const required = ["savejob", "getjob", "updatejob", "listjobs", "saveevent", "listevents", "savesession", "readsession", "saveartifact", "getartifact", "savechunk", "getchunks"];
  for (const name of required) if (typeof repository?.[name] !== "function") throw new TypeError(`drizzle repository requires ${name}`);
  return persistenceadapter(repository);
}
