name: saddle
on:
  workflow_dispatch:
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26.7.0
      - run: npm ci
      - run: npm run check
      - run: npm run formatcheck
      - run: npm test
      - run: npm run pack:check
