[package]
name = "saddle-desktop"
version = "1.8.9"
description = "Saddle desktop browser shell"
authors = ["wenathlan"]
edition = "2021"
build = "build.rs"

[lib]
name = "saddle_desktop"
path = "lib.rs"

[[bin]]
name = "saddle-desktop"
path = "main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
